"""
200 самых употребляемых неправильных глаголов английского языка.
Формат: (форма 1, форма 2, форма 3, перевод, пример со 2 формой, пример с 3 формой)
"""

IRREGULAR_VERBS = [
    ("be", "was/were", "been", "быть", "I was at home yesterday.", "I have been there before."),
    ("have", "had", "had", "иметь", "I had a car last year.", "I have had this book for a week."),
    ("do", "did", "done", "делать", "I did my homework.", "I have done the work."),
    ("say", "said", "said", "говорить", "He said hello.", "I have said it many times."),
    ("go", "went", "gone", "идти", "I went to the store.", "She has gone home."),
    ("get", "got", "got/gotten", "получать", "I got a letter.", "I have got a new job."),
    ("make", "made", "made", "делать", "I made a cake.", "I have made a mistake."),
    ("know", "knew", "known", "знать", "I knew the answer.", "I have known him for years."),
    ("think", "thought", "thought", "думать", "I thought about it.", "I have thought it over."),
    ("take", "took", "taken", "брать", "I took a book.", "I have taken the test."),
    ("see", "saw", "seen", "видеть", "I saw a movie.", "I have seen this film."),
    ("come", "came", "come", "приходить", "He came yesterday.", "He has come here."),
    ("want", "wanted", "wanted", "хотеть", "I wanted to go.", "I have wanted this for long."),
    ("use", "used", "used", "использовать", "I used this tool.", "I have used it before."),
    ("find", "found", "found", "находить", "I found my keys.", "I have found the solution."),
    ("give", "gave", "given", "давать", "I gave him a book.", "I have given you my word."),
    ("tell", "told", "told", "рассказывать", "I told him the truth.", "I have told you before."),
    ("work", "worked", "worked", "работать", "I worked hard.", "I have worked here for 5 years."),
    ("call", "called", "called", "звонить", "I called you.", "I have called him twice."),
    ("try", "tried", "tried", "пытаться", "I tried to help.", "I have tried everything."),
    ("ask", "asked", "asked", "спрашивать", "I asked a question.", "I have asked you before."),
    ("need", "needed", "needed", "нуждаться", "I needed help.", "I have needed this for long."),
    ("feel", "felt", "felt", "чувствовать", "I felt tired.", "I have felt better."),
    ("become", "became", "become", "становиться", "He became a doctor.", "He has become famous."),
    ("leave", "left", "left", "оставлять", "I left early.", "I have left my keys at home."),
    ("put", "put", "put", "класть", "I put it there.", "I have put it away."),
    ("mean", "meant", "meant", "значить", "It meant a lot.", "It has meant nothing."),
    ("keep", "kept", "kept", "хранить", "I kept it safe.", "I have kept this secret."),
    ("let", "let", "let", "позволять", "I let him go.", "I have let you know."),
    ("begin", "began", "begun", "начинать", "I began to study.", "I have begun a new project."),
    ("seem", "seemed", "seemed", "казаться", "It seemed easy.", "It has seemed difficult."),
    ("help", "helped", "helped", "помогать", "I helped him.", "I have helped many people."),
    ("show", "showed", "shown", "показывать", "I showed the way.", "I have shown you before."),
    ("hear", "heard", "heard", "слышать", "I heard the news.", "I have heard this song."),
    ("play", "played", "played", "играть", "I played football.", "I have played this game."),
    ("run", "ran", "run", "бежать", "I ran fast.", "I have run a marathon."),
    ("move", "moved", "moved", "двигаться", "I moved to a new city.", "I have moved here recently."),
    ("like", "liked", "liked", "нравиться", "I liked the movie.", "I have liked it for years."),
    ("live", "lived", "lived", "жить", "I lived in Moscow.", "I have lived here for 10 years."),
    ("believe", "believed", "believed", "верить", "I believed him.", "I have believed in you."),
    ("bring", "brought", "brought", "приносить", "I brought food.", "I have brought my friend."),
    ("happen", "happened", "happened", "происходить", "It happened yesterday.", "It has happened before."),
    ("write", "wrote", "written", "писать", "I wrote a letter.", "I have written a book."),
    ("sit", "sat", "sat", "сидеть", "I sat down.", "I have sat here before."),
    ("stand", "stood", "stood", "стоять", "I stood up.", "I have stood there for hours."),
    ("lose", "lost", "lost", "терять", "I lost my keys.", "I have lost my wallet."),
    ("pay", "paid", "paid", "платить", "I paid the bill.", "I have paid for it."),
    ("meet", "met", "met", "встречать", "I met him yesterday.", "I have met her before."),
    ("include", "included", "included", "включать", "I included everyone.", "I have included all data."),
    ("continue", "continued", "continued", "продолжать", "I continued working.", "I have continued the project."),
    ("set", "set", "set", "устанавливать", "I set the time.", "I have set the alarm."),
    ("learn", "learned/learnt", "learned/learnt", "учить", "I learned English.", "I have learned a lot."),
    ("change", "changed", "changed", "менять", "I changed my mind.", "I have changed my plans."),
    ("lead", "led", "led", "вести", "He led the team.", "He has led the company."),
    ("understand", "understood", "understood", "понимать", "I understood the problem.", "I have understood it now."),
    ("watch", "watched", "watched", "смотреть", "I watched TV.", "I have watched this show."),
    ("follow", "followed", "followed", "следовать", "I followed the rules.", "I have followed your advice."),
    ("stop", "stopped", "stopped", "останавливать", "I stopped the car.", "I have stopped smoking."),
    ("create", "created", "created", "создавать", "I created a website.", "I have created many projects."),
    ("speak", "spoke", "spoken", "говорить", "I spoke to him.", "I have spoken with her."),
    ("read", "read", "read", "читать", "I read a book.", "I have read this article."),
    ("spend", "spent", "spent", "тратить", "I spent money.", "I have spent all my savings."),
    ("grow", "grew", "grown", "расти", "I grew tomatoes.", "I have grown a lot."),
    ("open", "opened", "opened", "открывать", "I opened the door.", "I have opened a new business."),
    ("walk", "walked", "walked", "ходить", "I walked home.", "I have walked 5 km today."),
    ("win", "won", "won", "выигрывать", "I won the game.", "I have won many times."),
    ("teach", "taught", "taught", "учить", "I taught English.", "I have taught for 10 years."),
    ("offer", "offered", "offered", "предлагать", "I offered help.", "I have offered my services."),
    ("remember", "remembered", "remembered", "помнить", "I remembered the name.", "I have remembered it now."),
    ("consider", "considered", "considered", "рассматривать", "I considered the options.", "I have considered all factors."),
    ("appear", "appeared", "appeared", "появляться", "He appeared suddenly.", "He has appeared on TV."),
    ("buy", "bought", "bought", "покупать", "I bought a car.", "I have bought a house."),
    ("serve", "served", "served", "служить", "I served in the army.", "I have served for 5 years."),
    ("die", "died", "died", "умирать", "The plant died.", "Many people have died."),
    ("send", "sent", "sent", "отправлять", "I sent a letter.", "I have sent the package."),
    ("build", "built", "built", "строить", "I built a house.", "I have built many things."),
    ("stay", "stayed", "stayed", "оставаться", "I stayed home.", "I have stayed here for a week."),
    ("fall", "fell", "fallen", "падать", "I fell down.", "I have fallen many times."),
    ("cut", "cut", "cut", "резать", "I cut the paper.", "I have cut my finger."),
    ("reach", "reached", "reached", "достигать", "I reached the goal.", "I have reached the top."),
    ("kill", "killed", "killed", "убивать", "The hunter killed a deer.", "I have killed time."),
    ("raise", "raised", "raised", "поднимать", "I raised my hand.", "I have raised three children."),
    ("pass", "passed", "passed", "проходить", "I passed the exam.", "I have passed the test."),
    ("sell", "sold", "sold", "продавать", "I sold my car.", "I have sold everything."),
    ("decide", "decided", "decided", "решать", "I decided to go.", "I have decided to stay."),
    ("return", "returned", "returned", "возвращаться", "I returned home.", "I have returned the book."),
    ("explain", "explained", "explained", "объяснять", "I explained the rule.", "I have explained it many times."),
    ("develop", "developed", "developed", "развивать", "I developed the app.", "I have developed new skills."),
    ("carry", "carried", "carried", "нести", "I carried the bag.", "I have carried this burden."),
    ("break", "broke", "broken", "ломать", "I broke the glass.", "I have broken my promise."),
    ("receive", "received", "received", "получать", "I received a letter.", "I have received the package."),
    ("agree", "agreed", "agreed", "соглашаться", "I agreed with him.", "I have agreed to help."),
    ("support", "supported", "supported", "поддерживать", "I supported the idea.", "I have supported you always."),
    ("hit", "hit", "hit", "ударять", "I hit the ball.", "I have hit the target."),
    ("produce", "produced", "produced", "производить", "The factory produced cars.", "I have produced results."),
    ("eat", "ate", "eaten", "есть", "I ate breakfast.", "I have eaten lunch."),
    ("cover", "covered", "covered", "покрывать", "I covered the table.", "I have covered all topics."),
    ("catch", "caught", "caught", "ловить", "I caught the ball.", "I have caught a cold."),
    ("draw", "drew", "drawn", "рисовать", "I drew a picture.", "I have drawn many sketches."),
    ("choose", "chose", "chosen", "выбирать", "I chose the red one.", "I have chosen wisely."),
    ("wear", "wore", "worn", "носить", "I wore a coat.", "I have worn this dress."),
    ("throw", "threw", "thrown", "бросать", "I threw the ball.", "I have thrown it away."),
    ("fight", "fought", "fought", "бороться", "I fought for my rights.", "I have fought many battles."),
    ("shut", "shut", "shut", "закрывать", "I shut the door.", "I have shut the window."),
    ("deal", "dealt", "dealt", "иметь дело", "I dealt with the problem.", "I have dealt with this before."),
    ("spread", "spread", "spread", "распространять", "I spread the news.", "I have spread the butter."),
    ("strike", "struck", "struck", "ударять", "Lightning struck the tree.", "I have struck a deal."),
    ("stick", "stuck", "stuck", "прилипать", "The glue stuck.", "I have stuck to my plan."),
    ("win", "won", "won", "выигрывать", "I won the race.", "I have won the prize."),
    ("hang", "hung", "hung", "вешать", "I hung the picture.", "I have hung my coat."),
    ("shoot", "shot", "shot", "стрелять", "I shot the target.", "I have shot many photos."),
    ("lay", "laid", "laid", "класть", "I laid the book down.", "I have laid the foundation."),
    ("lie", "lay", "lain", "лежать", "I lay on the bed.", "I have lain here for hours."),
    ("lead", "led", "led", "вести", "He led the way.", "He has led the team."),
    ("feed", "fed", "fed", "кормить", "I fed the cat.", "I have fed the animals."),
    ("feel", "felt", "felt", "чувствовать", "I felt happy.", "I have felt better."),
    ("find", "found", "found", "находить", "I found my keys.", "I have found the answer."),
    ("fly", "flew", "flown", "летать", "I flew to Paris.", "I have flown many times."),
    ("forget", "forgot", "forgotten", "забывать", "I forgot the name.", "I have forgotten the password."),
    ("forgive", "forgave", "forgiven", "прощать", "I forgave him.", "I have forgiven you."),
    ("freeze", "froze", "frozen", "замерзать", "The water froze.", "I have frozen the food."),
    ("get", "got", "got/gotten", "получать", "I got a letter.", "I have got a new job."),
    ("give", "gave", "given", "давать", "I gave him a book.", "I have given you my word."),
    ("go", "went", "gone", "идти", "I went to the store.", "She has gone home."),
    ("grow", "grew", "grown", "расти", "I grew tomatoes.", "I have grown a lot."),
    ("hang", "hung", "hung", "вешать", "I hung the picture.", "I have hung my coat."),
    ("hear", "heard", "heard", "слышать", "I heard the news.", "I have heard this song."),
    ("hide", "hid", "hidden", "прятать", "I hid the money.", "I have hidden the key."),
    ("hit", "hit", "hit", "ударять", "I hit the ball.", "I have hit the target."),
    ("hold", "held", "held", "держать", "I held the baby.", "I have held this position."),
    ("hurt", "hurt", "hurt", "причинять боль", "I hurt my leg.", "I have hurt myself."),
    ("keep", "kept", "kept", "хранить", "I kept it safe.", "I have kept this secret."),
    ("know", "knew", "known", "знать", "I knew the answer.", "I have known him for years."),
    ("lay", "laid", "laid", "класть", "I laid the book down.", "I have laid the foundation."),
    ("lead", "led", "led", "вести", "He led the way.", "He has led the team."),
    ("leave", "left", "left", "оставлять", "I left early.", "I have left my keys at home."),
    ("lend", "lent", "lent", "одалживать", "I lent him money.", "I have lent you my car."),
    ("let", "let", "let", "позволять", "I let him go.", "I have let you know."),
    ("lie", "lay", "lain", "лежать", "I lay on the bed.", "I have lain here for hours."),
    ("light", "lit", "lit", "зажигать", "I lit the candle.", "I have lit the fire."),
    ("lose", "lost", "lost", "терять", "I lost my keys.", "I have lost my wallet."),
    ("make", "made", "made", "делать", "I made a cake.", "I have made a mistake."),
    ("mean", "meant", "meant", "значить", "It meant a lot.", "It has meant nothing."),
    ("meet", "met", "met", "встречать", "I met him yesterday.", "I have met her before."),
    ("pay", "paid", "paid", "платить", "I paid the bill.", "I have paid for it."),
    ("put", "put", "put", "класть", "I put it there.", "I have put it away."),
    ("read", "read", "read", "читать", "I read a book.", "I have read this article."),
    ("ride", "rode", "ridden", "ехать", "I rode a bike.", "I have ridden a horse."),
    ("ring", "rang", "rung", "звонить", "The phone rang.", "I have rung the bell."),
    ("rise", "rose", "risen", "подниматься", "The sun rose.", "Prices have risen."),
    ("run", "ran", "run", "бежать", "I ran fast.", "I have run a marathon."),
    ("say", "said", "said", "говорить", "He said hello.", "I have said it many times."),
    ("see", "saw", "seen", "видеть", "I saw a movie.", "I have seen this film."),
    ("sell", "sold", "sold", "продавать", "I sold my car.", "I have sold everything."),
    ("send", "sent", "sent", "отправлять", "I sent a letter.", "I have sent the package."),
    ("set", "set", "set", "устанавливать", "I set the time.", "I have set the alarm."),
    ("shake", "shook", "shaken", "трясти", "I shook the bottle.", "I have shaken hands."),
    ("shine", "shone", "shone", "светить", "The sun shone.", "I have shone the light."),
    ("shoot", "shot", "shot", "стрелять", "I shot the target.", "I have shot many photos."),
    ("show", "showed", "shown", "показывать", "I showed the way.", "I have shown you before."),
    ("shut", "shut", "shut", "закрывать", "I shut the door.", "I have shut the window."),
    ("sing", "sang", "sung", "петь", "I sang a song.", "I have sung this before."),
    ("sink", "sank", "sunk", "тонуть", "The ship sank.", "I have sunk the boat."),
    ("sit", "sat", "sat", "сидеть", "I sat down.", "I have sat here before."),
    ("sleep", "slept", "slept", "спать", "I slept well.", "I have slept for 8 hours."),
    ("speak", "spoke", "spoken", "говорить", "I spoke to him.", "I have spoken with her."),
    ("spend", "spent", "spent", "тратить", "I spent money.", "I have spent all my savings."),
    ("spread", "spread", "spread", "распространять", "I spread the news.", "I have spread the butter."),
    ("stand", "stood", "stood", "стоять", "I stood up.", "I have stood there for hours."),
    ("steal", "stole", "stolen", "красть", "Someone stole my bike.", "I have stolen nothing."),
    ("stick", "stuck", "stuck", "прилипать", "The glue stuck.", "I have stuck to my plan."),
    ("strike", "struck", "struck", "ударять", "Lightning struck the tree.", "I have struck a deal."),
    ("swim", "swam", "swum", "плавать", "I swam in the pool.", "I have swum in the ocean."),
    ("take", "took", "taken", "брать", "I took a book.", "I have taken the test."),
    ("teach", "taught", "taught", "учить", "I taught English.", "I have taught for 10 years."),
    ("tear", "tore", "torn", "рвать", "I tore the paper.", "I have torn my shirt."),
    ("tell", "told", "told", "рассказывать", "I told him the truth.", "I have told you before."),
    ("think", "thought", "thought", "думать", "I thought about it.", "I have thought it over."),
    ("throw", "threw", "thrown", "бросать", "I threw the ball.", "I have thrown it away."),
    ("understand", "understood", "understood", "понимать", "I understood the problem.", "I have understood it now."),
    ("wake", "woke", "woken", "просыпаться", "I woke up early.", "I have woken at 6 AM."),
    ("wear", "wore", "worn", "носить", "I wore a coat.", "I have worn this dress."),
    ("win", "won", "won", "выигрывать", "I won the game.", "I have won many times."),
    ("write", "wrote", "written", "писать", "I wrote a letter.", "I have written a book."),
]
