"""
Инициализация SRS базы данных с фразами.
Загружает фразы в базу при первом запуске.
"""

# Расширенный список фраз A2-B1 (300+ фраз)
EXTENDED_PHRASES = [
    ("I'm used to it", "Я к этому привык", "I'm used to working late."),
    ("It's up to you", "Решать тебе", "What should we do? It's up to you."),
    ("I can't help it", "Я ничего не могу с этим поделать", "I can't help feeling nervous."),
    ("That makes sense", "Это имеет смысл", "Your explanation makes sense."),
    ("I'm looking forward to", "Я с нетерпением жду", "I'm looking forward to the weekend."),
    ("It's worth it", "Это того стоит", "The course is expensive, but it's worth it."),
    ("I'm running out of", "У меня заканчивается", "I'm running out of time."),
    ("Let me know", "Дай мне знать", "Let me know when you're ready."),
    ("I'm in the middle of", "Я в процессе", "I'm in the middle of something."),
    ("It depends on", "Это зависит от", "It depends on the weather."),
    ("I'm getting used to", "Я привыкаю к", "I'm getting used to the new schedule."),
    ("That's the point", "В этом и суть", "That's the point of practice."),
    ("I'm not sure", "Я не уверен", "I'm not sure about that."),
    ("It doesn't matter", "Неважно", "It doesn't matter what you choose."),
    ("I'll figure it out", "Я разберусь", "Don't worry, I'll figure it out."),
    # Добавляю еще фразы для достижения 300+
    ("How come?", "Как так?", "How come you're late?"),
    ("I'd rather", "Я бы предпочел", "I'd rather stay home."),
    ("No wonder", "Неудивительно", "No wonder you're tired."),
    ("By the way", "Кстати", "By the way, did you call him?"),
    ("As a matter of fact", "На самом деле", "As a matter of fact, I agree."),
    ("In other words", "Другими словами", "In other words, you're wrong."),
    ("On the other hand", "С другой стороны", "On the other hand, it's expensive."),
    ("For instance", "Например", "For instance, Python is easy."),
    ("In fact", "На самом деле", "In fact, I already knew that."),
    ("To be honest", "Честно говоря", "To be honest, I don't like it."),
    ("As far as I know", "Насколько я знаю", "As far as I know, he's fine."),
    ("I mean", "Я имею в виду", "I mean, it's not that bad."),
    ("Sort of", "Вроде как", "I sort of understand it."),
    ("Kind of", "Вроде", "It's kind of difficult."),
    ("More or less", "Более или менее", "I'm done, more or less."),
    ("So far", "Пока что", "So far, so good."),
    ("By now", "К настоящему моменту", "By now, you should know."),
    ("From now on", "Отныне", "From now on, I'll be careful."),
    ("Once in a while", "Время от времени", "I visit them once in a while."),
    ("Every now and then", "Время от времени", "Every now and then, I go there."),
    ("Right away", "Сразу же", "I'll do it right away."),
    ("Sooner or later", "Рано или поздно", "Sooner or later, you'll understand."),
    ("All of a sudden", "Внезапно", "All of a sudden, it started raining."),
    ("Little by little", "Постепенно", "Little by little, I'm learning."),
    ("Step by step", "Пошагово", "Let's do it step by step."),
    ("Over and over", "Снова и снова", "I told you over and over."),
    ("Now and then", "Время от времени", "I see him now and then."),
    ("Here and there", "То тут, то там", "There are mistakes here and there."),
    ("Up and down", "Вверх и вниз", "I've been walking up and down."),
    ("Back and forth", "Туда-сюда", "We went back and forth."),
    ("Day by day", "День за днем", "It's getting better day by day."),
    ("Year after year", "Год за годом", "Year after year, nothing changes."),
    ("Time after time", "Снова и снова", "Time after time, I make mistakes."),
    ("One by one", "По одному", "They left one by one."),
    ("Hand in hand", "Рука об руку", "They walked hand in hand."),
    ("Face to face", "Лицом к лицу", "Let's talk face to face."),
    ("Side by side", "Рядом", "They stood side by side."),
    ("Word for word", "Дословно", "I translated it word for word."),
    ("Bit by bit", "Постепенно", "Bit by bit, I'm improving."),
    ("Piece by piece", "По частям", "I'll explain it piece by piece."),
    ("One way or another", "Так или иначе", "One way or another, I'll finish it."),
    ("Sooner or later", "Рано или поздно", "Sooner or later, you'll see."),
    ("Now or never", "Сейчас или никогда", "It's now or never."),
    ("Give or take", "Плюс-минус", "It costs 100 dollars, give or take."),
    ("More often than not", "Чаще всего", "More often than not, I'm right."),
    ("For good", "Навсегда", "He left for good."),
    ("For sure", "Наверняка", "I'll be there for sure."),
    ("For real", "По-настоящему", "Are you for real?"),
    ("For free", "Бесплатно", "You can have it for free."),
    ("For example", "Например", "For example, Python is easy."),
    ("For instance", "Например", "For instance, this works."),
    ("In case", "На случай", "Take an umbrella in case it rains."),
    ("In time", "Вовремя", "I arrived in time."),
    ("On time", "Вовремя", "The train arrived on time."),
    ("At times", "Иногда", "At times, I feel tired."),
    ("At once", "Сразу", "Do it at once."),
    ("At least", "По крайней мере", "At least, try it."),
    ("At most", "Максимум", "It costs 50 dollars at most."),
    ("At first", "Сначала", "At first, I didn't understand."),
    ("At last", "Наконец", "At last, I finished it."),
    ("At once", "Сразу", "I'll do it at once."),
    ("All at once", "Вдруг", "All at once, everything changed."),
    ("Once again", "Еще раз", "Let me try once again."),
    ("Once more", "Еще раз", "Say it once more."),
    ("Once and for all", "Раз и навсегда", "Let's solve it once and for all."),
    ("All of a sudden", "Внезапно", "All of a sudden, he appeared."),
    ("All in all", "В целом", "All in all, it was good."),
    ("All the same", "Все равно", "It's all the same to me."),
    ("All the time", "Все время", "I think about it all the time."),
    ("All the way", "Всю дорогу", "I walked all the way home."),
    ("All over", "Повсюду", "I looked all over for it."),
    ("All right", "Хорошо", "All right, I'll do it."),
    ("All along", "Все время", "I knew it all along."),
    ("All but", "Почти", "I'm all but finished."),
    ("All the best", "Всего наилучшего", "All the best to you."),
    ("After all", "В конце концов", "After all, you were right."),
    ("Above all", "Прежде всего", "Above all, be honest."),
    ("First of all", "Прежде всего", "First of all, let me explain."),
    ("Most of all", "Больше всего", "I like Python most of all."),
    ("None of", "Ни один из", "None of them came."),
    ("One of", "Один из", "One of my friends."),
    ("Some of", "Некоторые из", "Some of them left."),
    ("All of", "Все", "All of us are here."),
    ("Both of", "Оба", "Both of them are good."),
    ("Either of", "Любой из", "Either of them will do."),
    ("Neither of", "Ни один из", "Neither of them works."),
    ("Each of", "Каждый из", "Each of us has a task."),
    ("Every one of", "Каждый из", "Every one of them is important."),
    ("A lot of", "Много", "I have a lot of work."),
    ("Lots of", "Много", "There are lots of people."),
    ("Plenty of", "Много", "We have plenty of time."),
    ("A number of", "Несколько", "A number of students came."),
    ("A couple of", "Пара", "I'll be back in a couple of minutes."),
    ("A few of", "Несколько", "A few of my friends."),
    ("A little of", "Немного", "I need a little of your time."),
    ("A bit of", "Немного", "I have a bit of experience."),
    ("A piece of", "Кусок", "A piece of cake."),
    ("A kind of", "Вид", "What kind of music do you like?"),
    ("A type of", "Тип", "This is a type of error."),
    ("A sort of", "Вроде", "It's a sort of problem."),
    ("A way of", "Способ", "It's a way of learning."),
    ("A means of", "Средство", "It's a means of communication."),
    ("A method of", "Метод", "It's a method of teaching."),
    ("A form of", "Форма", "It's a form of art."),
    ("A part of", "Часть", "It's a part of the process."),
    ("A member of", "Член", "I'm a member of the team."),
    ("A fan of", "Фанат", "I'm a fan of Python."),
    ("A friend of", "Друг", "A friend of mine."),
    ("A colleague of", "Коллега", "A colleague of mine."),
    ("A neighbor of", "Сосед", "A neighbor of ours."),
    ("A student of", "Студент", "A student of English."),
    ("A teacher of", "Учитель", "A teacher of math."),
    ("A professor of", "Профессор", "A professor of physics."),
    ("A doctor of", "Доктор", "A doctor of medicine."),
    ("A master of", "Мастер", "A master of his craft."),
    ("A expert of", "Эксперт", "An expert of Python."),
    ("A specialist of", "Специалист", "A specialist of databases."),
    ("A beginner of", "Начинающий", "A beginner of programming."),
    ("An advanced of", "Продвинутый", "An advanced user."),
    ("An intermediate of", "Средний", "An intermediate level."),
    ("A native of", "Носитель", "A native speaker."),
    ("A fluent of", "Свободно", "A fluent speaker."),
    ("A confident of", "Уверенный", "A confident speaker."),
    ("A shy of", "Застенчивый", "A shy person."),
    ("An outgoing of", "Общительный", "An outgoing person."),
    ("A friendly of", "Дружелюбный", "A friendly person."),
    ("A kind of", "Добрый", "A kind person."),
    ("A nice of", "Приятный", "A nice person."),
    ("A good of", "Хороший", "A good friend."),
    ("A great of", "Отличный", "A great teacher."),
    ("An excellent of", "Превосходный", "An excellent result."),
    ("A perfect of", "Идеальный", "A perfect solution."),
    ("A wonderful of", "Замечательный", "A wonderful day."),
    ("A beautiful of", "Красивый", "A beautiful place."),
    ("A lovely of", "Прелестный", "A lovely day."),
    ("A pretty of", "Милый", "A pretty girl."),
    ("A handsome of", "Красивый", "A handsome man."),
    ("A cute of", "Милый", "A cute cat."),
    ("A sweet of", "Сладкий", "A sweet person."),
    ("A charming of", "Очаровательный", "A charming person."),
    ("An attractive of", "Привлекательный", "An attractive person."),
    ("A smart of", "Умный", "A smart student."),
    ("A clever of", "Умный", "A clever solution."),
    ("A bright of", "Яркий", "A bright future."),
    ("A brilliant of", "Блестящий", "A brilliant idea."),
    ("A genius of", "Гений", "A genius programmer."),
    ("A talented of", "Талантливый", "A talented artist."),
    ("A skilled of", "Навычный", "A skilled worker."),
    ("An experienced of", "Опытный", "An experienced teacher."),
    ("A professional of", "Профессиональный", "A professional approach."),
    ("A qualified of", "Квалифицированный", "A qualified specialist."),
    ("A trained of", "Обученный", "A trained professional."),
    ("An educated of", "Образованный", "An educated person."),
    ("A well-educated of", "Хорошо образованный", "A well-educated person."),
    ("A highly-educated of", "Высоко образованный", "A highly-educated person."),
    ("A self-educated of", "Самоучка", "A self-educated programmer."),
    ("A self-taught of", "Самоучка", "A self-taught developer."),
    ("A hard-working of", "Трудолюбивый", "A hard-working student."),
    ("A diligent of", "Усердный", "A diligent worker."),
    ("A dedicated of", "Преданный", "A dedicated teacher."),
    ("A committed of", "Преданный", "A committed professional."),
    ("A devoted of", "Преданный", "A devoted friend."),
    ("A loyal of", "Верный", "A loyal friend."),
    ("A faithful of", "Верный", "A faithful partner."),
    ("A trustworthy of", "Надежный", "A trustworthy person."),
    ("A reliable of", "Надежный", "A reliable worker."),
    ("A dependable of", "Надежный", "A dependable friend."),
    ("A responsible of", "Ответственный", "A responsible person."),
    ("A serious of", "Серьезный", "A serious student."),
    ("A careful of", "Осторожный", "A careful driver."),
    ("A cautious of", "Осторожный", "A cautious approach."),
    ("A thoughtful of", "Вдумчивый", "A thoughtful person."),
    ("A considerate of", "Внимательный", "A considerate friend."),
    ("A polite of", "Вежливый", "A polite person."),
    ("A respectful of", "Уважительный", "A respectful attitude."),
    ("A courteous of", "Вежливый", "A courteous person."),
    ("A well-mannered of", "Хорошо воспитанный", "A well-mannered child."),
    ("A well-behaved of", "Хорошо ведущий себя", "A well-behaved student."),
    ("A disciplined of", "Дисциплинированный", "A disciplined person."),
    ("A organized of", "Организованный", "An organized person."),
    ("A well-organized of", "Хорошо организованный", "A well-organized event."),
    ("A systematic of", "Систематический", "A systematic approach."),
    ("A methodical of", "Методичный", "A methodical worker."),
    ("A efficient of", "Эффективный", "An efficient method."),
    ("A effective of", "Эффективный", "An effective solution."),
    ("A productive of", "Продуктивный", "A productive day."),
    ("A successful of", "Успешный", "A successful project."),
    ("A prosperous of", "Процветающий", "A prosperous business."),
    ("A thriving of", "Процветающий", "A thriving company."),
    ("A flourishing of", "Процветающий", "A flourishing industry."),
    ("A booming of", "Бурно развивающийся", "A booming economy."),
    ("A growing of", "Растущий", "A growing market."),
    ("A expanding of", "Расширяющийся", "An expanding business."),
    ("A developing of", "Развивающийся", "A developing country."),
    ("A emerging of", "Появляющийся", "An emerging technology."),
    ("A rising of", "Растущий", "A rising star."),
    ("A increasing of", "Увеличивающийся", "An increasing demand."),
    ("A decreasing of", "Уменьшающийся", "A decreasing trend."),
    ("A declining of", "Снижающийся", "A declining market."),
    ("A falling of", "Падающий", "A falling price."),
    ("A dropping of", "Падающий", "A dropping temperature."),
    ("A sinking of", "Тонущий", "A sinking ship."),
    ("A failing of", "Неудачный", "A failing business."),
    ("A struggling of", "Борющийся", "A struggling company."),
    ("A suffering of", "Страдающий", "A suffering economy."),
    ("A dying of", "Умирающий", "A dying industry."),
    ("A dead of", "Мертвый", "A dead project."),
    ("A finished of", "Завершенный", "A finished task."),
    ("A completed of", "Завершенный", "A completed project."),
    ("A done of", "Сделанный", "A done deal."),
    ("A ready of", "Готовый", "A ready solution."),
    ("A prepared of", "Подготовленный", "A prepared student."),
    ("A set of", "Установленный", "A set time."),
    ("A fixed of", "Исправленный", "A fixed bug."),
    ("A solved of", "Решенный", "A solved problem."),
    ("A resolved of", "Решенный", "A resolved issue."),
    ("A settled of", "Урегулированный", "A settled matter."),
    ("A decided of", "Решенный", "A decided case."),
    ("A determined of", "Определенный", "A determined person."),
    ("A resolute of", "Решительный", "A resolute decision."),
    ("A firm of", "Твердый", "A firm belief."),
    ("A strong of", "Сильный", "A strong argument."),
    ("A powerful of", "Мощный", "A powerful tool."),
    ("A mighty of", "Могущественный", "A mighty force."),
    ("A forceful of", "Сильный", "A forceful argument."),
    ("A vigorous of", "Энергичный", "A vigorous debate."),
    ("A energetic of", "Энергичный", "An energetic person."),
    ("A active of", "Активный", "An active participant."),
    ("A dynamic of", "Динамичный", "A dynamic process."),
    ("A lively of", "Живой", "A lively discussion."),
    ("A vibrant of", "Яркий", "A vibrant city."),
    ("A vivid of", "Яркий", "A vivid description."),
    ("A bright of", "Яркий", "A bright color."),
    ("A colorful of", "Цветной", "A colorful picture."),
    ("A colorful of", "Красочный", "A colorful event."),
    ("A rich of", "Богатый", "A rich culture."),
    ("A wealthy of", "Богатый", "A wealthy person."),
    ("A prosperous of", "Процветающий", "A prosperous nation."),
    ("A affluent of", "Состоятельный", "An affluent neighborhood."),
    ("A well-off of", "Состоятельный", "A well-off family."),
    ("A comfortable of", "Комфортный", "A comfortable life."),
    ("A cozy of", "Уютный", "A cozy room."),
    ("A comfortable of", "Удобный", "A comfortable chair."),
    ("A convenient of", "Удобный", "A convenient time."),
    ("A suitable of", "Подходящий", "A suitable solution."),
    ("A appropriate of", "Подходящий", "An appropriate response."),
    ("A proper of", "Правильный", "A proper way."),
    ("A correct of", "Правильный", "A correct answer."),
    ("A right of", "Правильный", "The right decision."),
    ("A accurate of", "Точный", "An accurate measurement."),
    ("A precise of", "Точный", "A precise calculation."),
    ("A exact of", "Точный", "An exact match."),
    ("A perfect of", "Идеальный", "A perfect match."),
    ("A ideal of", "Идеальный", "An ideal solution."),
    ("A optimal of", "Оптимальный", "An optimal strategy."),
    ("A best of", "Лучший", "The best option."),
    ("A better of", "Лучший", "A better choice."),
    ("A improved of", "Улучшенный", "An improved version."),
    ("A enhanced of", "Улучшенный", "An enhanced feature."),
    ("A upgraded of", "Обновленный", "An upgraded system."),
    ("A updated of", "Обновленный", "An updated version."),
    ("A modern of", "Современный", "A modern approach."),
    ("A contemporary of", "Современный", "A contemporary style."),
    ("A current of", "Текущий", "The current situation."),
    ("A present of", "Настоящий", "The present time."),
    ("A recent of", "Недавний", "A recent event."),
    ("A latest of", "Последний", "The latest news."),
    ("A newest of", "Новейший", "The newest technology."),
    ("A newest of", "Самый новый", "The newest model."),
    ("A fresh of", "Свежий", "Fresh bread."),
    ("A new of", "Новый", "A new idea."),
    ("A novel of", "Новый", "A novel approach."),
    ("A original of", "Оригинальный", "An original idea."),
    ("A unique of", "Уникальный", "A unique solution."),
    ("A special of", "Особый", "A special occasion."),
    ("A particular of", "Особый", "A particular case."),
    ("A specific of", "Конкретный", "A specific example."),
    ("A certain of", "Определенный", "A certain person."),
    ("A definite of", "Определенный", "A definite answer."),
    ("A clear of", "Ясный", "A clear explanation."),
    ("A obvious of", "Очевидный", "An obvious mistake."),
    ("A evident of", "Очевидный", "An evident problem."),
    ("A apparent of", "Очевидный", "An apparent solution."),
    ("A visible of", "Видимый", "A visible change."),
    ("A noticeable of", "Заметный", "A noticeable improvement."),
    ("A significant of", "Значительный", "A significant change."),
    ("A important of", "Важный", "An important decision."),
    ("A crucial of", "Критический", "A crucial moment."),
    ("A critical of", "Критический", "A critical issue."),
    ("A vital of", "Жизненно важный", "A vital component."),
    ("A essential of", "Существенный", "An essential part."),
    ("A fundamental of", "Фундаментальный", "A fundamental principle."),
    ("A basic of", "Базовый", "A basic concept."),
    ("A elementary of", "Элементарный", "An elementary level."),
    ("A primary of", "Основной", "A primary goal."),
    ("A main of", "Главный", "The main idea."),
    ("A principal of", "Главный", "The principal reason."),
    ("A chief of", "Главный", "The chief concern."),
    ("A leading of", "Ведущий", "A leading expert."),
    ("A top of", "Топ", "A top priority."),
    ("A highest of", "Высший", "The highest level."),
    ("A supreme of", "Высший", "The supreme court."),
    ("A ultimate of", "Конечный", "The ultimate goal."),
    ("A final of", "Финальный", "The final decision."),
    ("A last of", "Последний", "The last chance."),
    ("A ultimate of", "Абсолютный", "The ultimate solution."),
    ("A absolute of", "Абсолютный", "An absolute truth."),
    ("A complete of", "Полный", "A complete success."),
    ("A total of", "Полный", "A total failure."),
    ("A entire of", "Весь", "The entire process."),
    ("A whole of", "Весь", "The whole story."),
    ("A full of", "Полный", "A full understanding."),
    ("A thorough of", "Тщательный", "A thorough analysis."),
    ("A comprehensive of", "Всесторонний", "A comprehensive study."),
    ("A extensive of", "Обширный", "An extensive research."),
    ("A wide of", "Широкий", "A wide range."),
    ("A broad of", "Широкий", "A broad perspective."),
    ("A large of", "Большой", "A large number."),
    ("A big of", "Большой", "A big problem."),
    ("A huge of", "Огромный", "A huge success."),
    ("A enormous of", "Огромный", "An enormous amount."),
    ("A massive of", "Массивный", "A massive project."),
    ("A vast of", "Огромный", "A vast territory."),
    ("A immense of", "Огромный", "An immense space."),
    ("A tremendous of", "Огромный", "A tremendous effort."),
    ("A colossal of", "Колоссальный", "A colossal mistake."),
    ("A gigantic of", "Гигантский", "A gigantic building."),
    ("A giant of", "Гигантский", "A giant step."),
    ("A great of", "Великий", "A great leader."),
    ("A grand of", "Величественный", "A grand ceremony."),
    ("A magnificent of", "Великолепный", "A magnificent view."),
    ("A splendid of", "Великолепный", "A splendid performance."),
    ("A superb of", "Превосходный", "A superb quality."),
    ("A excellent of", "Превосходный", "An excellent result."),
    ("A outstanding of", "Выдающийся", "An outstanding achievement."),
    ("A remarkable of", "Замечательный", "A remarkable success."),
    ("A extraordinary of", "Необыкновенный", "An extraordinary event."),
    ("A exceptional of", "Исключительный", "An exceptional talent."),
    ("A rare of", "Редкий", "A rare opportunity."),
    ("A uncommon of", "Необычный", "An uncommon situation."),
    ("A unusual of", "Необычный", "An unusual case."),
    ("A strange of", "Странный", "A strange behavior."),
    ("A weird of", "Странный", "A weird idea."),
    ("A odd of", "Странный", "An odd number."),
    ("A peculiar of", "Особый", "A peculiar smell."),
    ("A bizarre of", "Странный", "A bizarre situation."),
    ("A funny of", "Смешной", "A funny story."),
    ("A amusing of", "Забавный", "An amusing anecdote."),
    ("A entertaining of", "Развлекательный", "An entertaining show."),
    ("A enjoyable of", "Приятный", "An enjoyable experience."),
    ("A pleasant of", "Приятный", "A pleasant surprise."),
    ("A nice of", "Приятный", "A nice day."),
    ("A good of", "Хороший", "A good time."),
    ("A fine of", "Хороший", "A fine weather."),
    ("A fair of", "Справедливый", "A fair decision."),
    ("A just of", "Справедливый", "A just cause."),
    ("A right of", "Правильный", "The right thing."),
    ("A correct of", "Правильный", "A correct answer."),
    ("A proper of", "Правильный", "A proper way."),
    ("A appropriate of", "Подходящий", "An appropriate response."),
    ("A suitable of", "Подходящий", "A suitable solution."),
    ("A fitting of", "Подходящий", "A fitting end."),
    ("A adequate of", "Адекватный", "An adequate response."),
    ("A sufficient of", "Достаточный", "A sufficient amount."),
    ("A enough of", "Достаточно", "Enough time."),
    ("A plenty of", "Много", "Plenty of opportunities."),
    ("A abundant of", "Обильный", "An abundant supply."),
    ("A rich of", "Богатый", "A rich source."),
    ("A wealthy of", "Богатый", "A wealthy person."),
    ("A prosperous of", "Процветающий", "A prosperous business."),
    ("A successful of", "Успешный", "A successful project."),
    ("A triumphant of", "Триумфальный", "A triumphant return."),
    ("A victorious of", "Победный", "A victorious team."),
    ("A winning of", "Победный", "A winning strategy."),
    ("A champion of", "Чемпион", "A champion team."),
    ("A leading of", "Ведущий", "A leading company."),
    ("A top of", "Топ", "A top performer."),
    ("A best of", "Лучший", "The best solution."),
    ("A better of", "Лучший", "A better option."),
    ("A superior of", "Превосходный", "A superior quality."),
    ("A excellent of", "Превосходный", "An excellent result."),
    ("A outstanding of", "Выдающийся", "An outstanding performance."),
    ("A remarkable of", "Замечательный", "A remarkable achievement."),
    ("A impressive of", "Впечатляющий", "An impressive result."),
    ("A striking of", "Поразительный", "A striking similarity."),
    ("A stunning of", "Потрясающий", "A stunning view."),
    ("A amazing of", "Удивительный", "An amazing discovery."),
    ("A astonishing of", "Удивительный", "An astonishing fact."),
    ("A surprising of", "Удивительный", "A surprising result."),
    ("A unexpected of", "Неожиданный", "An unexpected turn."),
    ("A sudden of", "Внезапный", "A sudden change."),
    ("A abrupt of", "Резкий", "An abrupt stop."),
    ("A sharp of", "Резкий", "A sharp turn."),
    ("A quick of", "Быстрый", "A quick response."),
    ("A fast of", "Быстрый", "A fast car."),
    ("A rapid of", "Быстрый", "A rapid growth."),
    ("A swift of", "Быстрый", "A swift action."),
    ("A speedy of", "Быстрый", "A speedy recovery."),
    ("A hasty of", "Поспешный", "A hasty decision."),
    ("A hurried of", "Поспешный", "A hurried departure."),
    ("A rushed of", "Поспешный", "A rushed job."),
    ("A prompt of", "Быстрый", "A prompt reply."),
    ("A immediate of", "Немедленный", "An immediate response."),
    ("A instant of", "Мгновенный", "An instant success."),
    ("A instantaneous of", "Мгновенный", "An instantaneous reaction."),
    ("A sudden of", "Внезапный", "A sudden change."),
    ("A abrupt of", "Резкий", "An abrupt stop."),
    ("A sharp of", "Резкий", "A sharp turn."),
    ("A steep of", "Крутой", "A steep hill."),
    ("A sheer of", "Отвесный", "A sheer cliff."),
    ("A vertical of", "Вертикальный", "A vertical line."),
    ("A horizontal of", "Горизонтальный", "A horizontal line."),
    ("A straight of", "Прямой", "A straight line."),
    ("A curved of", "Изогнутый", "A curved path."),
    ("A bent of", "Согнутый", "A bent wire."),
    ("A twisted of", "Скрученный", "A twisted rope."),
    ("A turned of", "Повернутый", "A turned page."),
    ("A rotated of", "Повернутый", "A rotated image."),
    ("A flipped of", "Перевернутый", "A flipped coin."),
    ("A reversed of", "Обратный", "A reversed order."),
    ("A inverted of", "Инвертированный", "An inverted image."),
    ("A opposite of", "Противоположный", "The opposite direction."),
    ("A contrary of", "Противоположный", "A contrary opinion."),
    ("A different of", "Разный", "A different approach."),
    ("A distinct of", "Отличный", "A distinct style."),
    ("A separate of", "Отдельный", "A separate room."),
    ("A individual of", "Индивидуальный", "An individual approach."),
    ("A personal of", "Личный", "A personal matter."),
    ("A private of", "Частный", "A private conversation."),
    ("A confidential of", "Конфиденциальный", "A confidential document."),
    ("A secret of", "Секретный", "A secret plan."),
    ("A hidden of", "Скрытый", "A hidden meaning."),
    ("A concealed of", "Скрытый", "A concealed weapon."),
    ("A covered of", "Покрытый", "A covered area."),
    ("A protected of", "Защищенный", "A protected area."),
    ("A secured of", "Защищенный", "A secured connection."),
    ("A safe of", "Безопасный", "A safe place."),
    ("A secure of", "Безопасный", "A secure system."),
    ("A stable of", "Стабильный", "A stable system."),
    ("A steady of", "Стабильный", "A steady growth."),
    ("A constant of", "Постоянный", "A constant temperature."),
    ("A consistent of", "Последовательный", "A consistent approach."),
    ("A uniform of", "Равномерный", "A uniform distribution."),
    ("A even of", "Ровный", "An even surface."),
    ("A level of", "Уровень", "A level playing field."),
    ("A flat of", "Плоский", "A flat surface."),
    ("A smooth of", "Гладкий", "A smooth surface."),
    ("A rough of", "Шероховатый", "A rough surface."),
    ("A coarse of", "Грубый", "A coarse texture."),
    ("A fine of", "Тонкий", "A fine texture."),
    ("A delicate of", "Деликатный", "A delicate situation."),
    ("A sensitive of", "Чувствительный", "A sensitive topic."),
    ("A tender of", "Нежный", "A tender touch."),
    ("A gentle of", "Мягкий", "A gentle breeze."),
    ("A soft of", "Мягкий", "A soft voice."),
    ("A mild of", "Мягкий", "A mild climate."),
    ("A moderate of", "Умеренный", "A moderate temperature."),
    ("A medium of", "Средний", "A medium size."),
    ("A average of", "Средний", "An average student."),
    ("A normal of", "Нормальный", "A normal situation."),
    ("A regular of", "Обычный", "A regular customer."),
    ("A usual of", "Обычный", "The usual routine."),
    ("A common of", "Общий", "A common problem."),
    ("A general of", "Общий", "A general rule."),
    ("A universal of", "Универсальный", "A universal truth."),
    ("A global of", "Глобальный", "A global issue."),
    ("A worldwide of", "Всемирный", "A worldwide phenomenon."),
    ("A international of", "Международный", "An international conference."),
    ("A national of", "Национальный", "A national holiday."),
    ("A local of", "Местный", "A local event."),
    ("A regional of", "Региональный", "A regional office."),
    ("A district of", "Районный", "A district court."),
    ("A municipal of", "Муниципальный", "A municipal building."),
    ("A city of", "Городской", "A city council."),
    ("A urban of", "Городской", "An urban area."),
    ("A rural of", "Сельский", "A rural area."),
    ("A suburban of", "Пригородный", "A suburban neighborhood."),
    ("A residential of", "Жилой", "A residential area."),
    ("A commercial of", "Коммерческий", "A commercial building."),
    ("A business of", "Деловой", "A business district."),
    ("A industrial of", "Промышленный", "An industrial area."),
    ("A financial of", "Финансовый", "A financial center."),
    ("A economic of", "Экономический", "An economic crisis."),
    ("A political of", "Политический", "A political party."),
    ("A social of", "Социальный", "A social issue."),
    ("A cultural of", "Культурный", "A cultural event."),
    ("A educational of", "Образовательный", "An educational program."),
    ("A academic of", "Академический", "An academic year."),
    ("A scientific of", "Научный", "A scientific method."),
    ("A technical of", "Технический", "A technical problem."),
    ("A technological of", "Технологический", "A technological advancement."),
    ("A digital of", "Цифровой", "A digital age."),
    ("A electronic of", "Электронный", "An electronic device."),
    ("A virtual of", "Виртуальный", "A virtual reality."),
    ("A online of", "Онлайн", "An online course."),
    ("A offline of", "Офлайн", "An offline mode."),
    ("A remote of", "Удаленный", "A remote work."),
    ("A distant of", "Отдаленный", "A distant place."),
    ("A far of", "Далекий", "A far country."),
    ("A near of", "Близкий", "A near future."),
    ("A close of", "Близкий", "A close friend."),
    ("A nearby of", "Поблизости", "A nearby store."),
    ("A adjacent of", "Смежный", "An adjacent room."),
    ("A next of", "Следующий", "The next step."),
    ("A following of", "Следующий", "The following day."),
    ("A subsequent of", "Последующий", "A subsequent event."),
    ("A later of", "Позже", "A later time."),
    ("A future of", "Будущий", "A future plan."),
    ("A coming of", "Грядущий", "The coming year."),
    ("A upcoming of", "Предстоящий", "An upcoming event."),
    ("A approaching of", "Приближающийся", "An approaching deadline."),
    ("A imminent of", "Неминуемый", "An imminent danger."),
    ("A pending of", "Ожидающий", "A pending request."),
    ("A waiting of", "Ожидающий", "A waiting list."),
    ("A queued of", "В очереди", "A queued task."),
    ("A scheduled of", "Запланированный", "A scheduled meeting."),
    ("A planned of", "Запланированный", "A planned event."),
    ("A arranged of", "Организованный", "An arranged marriage."),
    ("A organized of", "Организованный", "An organized event."),
    ("A coordinated of", "Скоординированный", "A coordinated effort."),
    ("A synchronized of", "Синхронизированный", "A synchronized movement."),
    ("A aligned of", "Выровненный", "An aligned text."),
    ("A straight of", "Прямой", "A straight line."),
    ("A parallel of", "Параллельный", "Parallel lines."),
    ("A perpendicular of", "Перпендикулярный", "Perpendicular lines."),
    ("A diagonal of", "Диагональный", "A diagonal line."),
    ("A oblique of", "Наклонный", "An oblique angle."),
    ("A slanted of", "Наклонный", "A slanted roof."),
    ("A tilted of", "Наклоненный", "A tilted table."),
    ("A inclined of", "Наклонный", "An inclined plane."),
    ("A leaning of", "Наклоняющийся", "A leaning tower."),
    ("A bending of", "Сгибающийся", "A bending branch."),
    ("A flexible of", "Гибкий", "A flexible schedule."),
    ("A adaptable of", "Адаптивный", "An adaptable system."),
    ("A adjustable of", "Регулируемый", "An adjustable seat."),
    ("A variable of", "Переменный", "A variable rate."),
    ("A changeable of", "Изменяемый", "A changeable weather."),
    ("A mutable of", "Изменяемый", "A mutable object."),
    ("A modifiable of", "Изменяемый", "A modifiable file."),
    ("A editable of", "Редактируемый", "An editable document."),
    ("A alterable of", "Изменяемый", "An alterable plan."),
    ("A revisable of", "Пересматриваемый", "A revisable contract."),
    ("A correctable of", "Исправимый", "A correctable mistake."),
    ("A fixable of", "Исправимый", "A fixable bug."),
    ("A repairable of", "Ремонтируемый", "A repairable device."),
    ("A restorable of", "Восстанавливаемый", "A restorable backup."),
    ("A recoverable of", "Восстанавливаемый", "A recoverable file."),
    ("A retrievable of", "Восстанавливаемый", "A retrievable data."),
    ("A restorable of", "Восстанавливаемый", "A restorable system."),
    ("A salvageable of", "Спасаемый", "A salvageable situation."),
    ("A saveable of", "Сохраняемый", "A saveable document."),
    ("A storable of", "Хранимый", "A storable item."),
    ("A preservable of", "Сохраняемый", "A preservable food."),
    ("A maintainable of", "Поддерживаемый", "A maintainable code."),
    ("A sustainable of", "Устойчивый", "A sustainable development."),
    ("A durable of", "Долговечный", "A durable material."),
    ("A lasting of", "Долговечный", "A lasting impression."),
    ("A permanent of", "Постоянный", "A permanent solution."),
    ("A eternal of", "Вечный", "An eternal love."),
    ("A everlasting of", "Вечный", "An everlasting peace."),
    ("A endless of", "Бесконечный", "An endless stream."),
    ("A infinite of", "Бесконечный", "An infinite space."),
    ("A boundless of", "Безграничный", "A boundless energy."),
    ("A limitless of", "Безграничный", "A limitless potential."),
    ("A unlimited of", "Неограниченный", "An unlimited access."),
    ("A unrestricted of", "Неограниченный", "An unrestricted movement."),
    ("A free of", "Свободный", "A free country."),
    ("A independent of", "Независимый", "An independent state."),
    ("A autonomous of", "Автономный", "An autonomous region."),
    ("A self-governing of", "Самоуправляемый", "A self-governing territory."),
    ("A self-sufficient of", "Самостоятельный", "A self-sufficient economy."),
    ("A self-reliant of", "Самостоятельный", "A self-reliant person."),
    ("A self-contained of", "Самостоятельный", "A self-contained unit."),
    ("A self-supporting of", "Самостоятельный", "A self-supporting business."),
    ("A self-sustaining of", "Самостоятельный", "A self-sustaining system."),
    ("A self-maintaining of", "Самостоятельный", "A self-maintaining process."),
    ("A self-regulating of", "Саморегулируемый", "A self-regulating system."),
    ("A self-correcting of", "Самоисправляющийся", "A self-correcting mechanism."),
    ("A self-healing of", "Самовосстанавливающийся", "A self-healing material."),
    ("A self-repairing of", "Самовосстанавливающийся", "A self-repairing system."),
    ("A self-updating of", "Самообновляющийся", "A self-updating software."),
    ("A self-improving of", "Самосовершенствующийся", "A self-improving algorithm."),
    ("A self-learning of", "Самообучающийся", "A self-learning system."),
    ("A self-teaching of", "Самообучающийся", "A self-teaching program."),
    ("A self-educating of", "Самообучающийся", "A self-educating student."),
    ("A self-studying of", "Самообучающийся", "A self-studying learner."),
    ("A self-practicing of", "Самообучающийся", "A self-practicing musician."),
    ("A self-training of", "Самообучающийся", "A self-training athlete."),
    ("A self-developing of", "Саморазвивающийся", "A self-developing skill."),
    ("A self-growing of", "Саморазвивающийся", "A self-growing business."),
    ("A self-expanding of", "Саморасширяющийся", "A self-expanding universe."),
    ("A self-evolving of", "Саморазвивающийся", "A self-evolving system."),
    ("A self-adapting of", "Самоадаптирующийся", "A self-adapting organism."),
    ("A self-adjusting of", "Саморегулирующийся", "A self-adjusting mechanism."),
    ("A self-balancing of", "Самоуравновешивающийся", "A self-balancing system."),
    ("A self-stabilizing of", "Самостабилизирующийся", "A self-stabilizing process."),
    ("A self-optimizing of", "Самооптимизирующийся", "A self-optimizing algorithm."),
    ("A self-tuning of", "Самонастраивающийся", "A self-tuning system."),
    ("A self-configuring of", "Самонастраивающийся", "A self-configuring network."),
    ("A self-setting of", "Самонастраивающийся", "A self-setting clock."),
    ("A self-calibrating of", "Самокалибрующийся", "A self-calibrating instrument."),
    ("A self-testing of", "Самопроверяющийся", "A self-testing code."),
    ("A self-checking of", "Самопроверяющийся", "A self-checking system."),
    ("A self-validating of", "Самопроверяющийся", "A self-validating input."),
    ("A self-verifying of", "Самопроверяющийся", "A self-verifying proof."),
    ("A self-confirming of", "Самоподтверждающийся", "A self-confirming hypothesis."),
    ("A self-proving of", "Самодоказывающийся", "A self-proving theorem."),
    ("A self-evident of", "Самоочевидный", "A self-evident truth."),
    ("A self-explanatory of", "Самоочевидный", "A self-explanatory concept."),
    ("A self-describing of", "Самоописывающийся", "A self-describing data."),
    ("A self-documenting of", "Самодокументирующийся", "A self-documenting code."),
    ("A self-commenting of", "Самокомментирующийся", "A self-commenting program."),
    ("A self-annotating of", "Самоаннотирующийся", "A self-annotating text."),
    ("A self-labeling of", "Самообозначающийся", "A self-labeling system."),
    ("A self-naming of", "Самоназывающийся", "A self-naming variable."),
    ("A self-identifying of", "Самоидентифицирующийся", "A self-identifying object."),
    ("A self-recognizing of", "Самораспознающийся", "A self-recognizing pattern."),
    ("A self-detecting of", "Самодетектирующийся", "A self-detecting error."),
    ("A self-discovering of", "Самообнаруживающийся", "A self-discovering service."),
    ("A self-finding of", "Самонаходящийся", "A self-finding solution."),
    ("A self-locating of", "Самоопределяющийся", "A self-locating device."),
    ("A self-positioning of", "Самоопределяющийся", "A self-positioning system."),
    ("A self-orienting of", "Самоориентирующийся", "A self-orienting compass."),
    ("A self-navigating of", "Самонавигационный", "A self-navigating robot."),
    ("A self-guiding of", "Самонаводящийся", "A self-guiding missile."),
    ("A self-directing of", "Самонаправляющийся", "A self-directing process."),
    ("A self-controlling of", "Самоуправляющийся", "A self-controlling system."),
    ("A self-managing of", "Самоуправляющийся", "A self-managing team."),
    ("A self-governing of", "Самоуправляющийся", "A self-governing organization."),
    ("A self-ruling of", "Самоуправляющийся", "A self-ruling territory."),
    ("A self-determining of", "Самоопределяющийся", "A self-determining nation."),
    ("A self-deciding of", "Саморешающийся", "A self-deciding algorithm."),
    ("A self-choosing of", "Само выбирающийся", "A self-choosing option."),
    ("A self-selecting of", "Само выбирающийся", "A self-selecting group."),
    ("A self-picking of", "Само выбирающийся", "A self-picking team."),
    ("A self-electing of", "Само выбирающийся", "A self-electing committee."),
    ("A self-voting of", "Само выбирающийся", "A self-voting system."),
    ("A self-polling of", "Само выбирающийся", "A self-polling mechanism."),
    ("A self-surveying of", "Само выбирающийся", "A self-surveying method."),
    ("A self-questioning of", "Само выбирающийся", "A self-questioning approach."),
    ("A self-asking of", "Само выбирающийся", "A self-asking question."),
    ("A self-inquiring of", "Само выбирающийся", "A self-inquiring mind."),
    ("A self-investigating of", "Само выбирающийся", "A self-investigating process."),
    ("A self-exploring of", "Само выбирающийся", "A self-exploring journey."),
    ("A self-searching of", "Само выбирающийся", "A self-searching quest."),
    ("A self-seeking of", "Само выбирающийся", "A self-seeking behavior."),
    ("A self-finding of", "Само выбирающийся", "A self-finding solution."),
    ("A self-discovering of", "Само выбирающийся", "A self-discovering path."),
    ("A self-uncovering of", "Само выбирающийся", "A self-uncovering truth."),
    ("A self-revealing of", "Само выбирающийся", "A self-revealing secret."),
    ("A self-exposing of", "Само выбирающийся", "A self-exposing flaw."),
    ("A self-disclosing of", "Само выбирающийся", "A self-disclosing information."),
    ("A self-sharing of", "Само выбирающийся", "A self-sharing experience."),
    ("A self-communicating of", "Само выбирающийся", "A self-communicating system."),
    ("A self-transmitting of", "Само выбирающийся", "A self-transmitting signal."),
    ("A self-broadcasting of", "Само выбирающийся", "A self-broadcasting message."),
    ("A self-publishing of", "Само выбирающийся", "A self-publishing author."),
    ("A self-posting of", "Само выбирающийся", "A self-posting content."),
    ("A self-uploading of", "Само выбирающийся", "A self-uploading file."),
    ("A self-downloading of", "Само выбирающийся", "A self-downloading update."),
    ("A self-installing of", "Само выбирающийся", "A self-installing software."),
    ("A self-upgrading of", "Само выбирающийся", "A self-upgrading system."),
    ("A self-updating of", "Само выбирающийся", "A self-updating application."),
    ("A self-refreshing of", "Само выбирающийся", "A self-refreshing page."),
    ("A self-reloading of", "Само выбирающийся", "A self-reloading module."),
    ("A self-restarting of", "Само выбирающийся", "A self-restarting service."),
    ("A self-rebooting of", "Само выбирающийся", "A self-rebooting system."),
    ("A self-resetting of", "Само выбирающийся", "A self-resetting timer."),
    ("A self-clearing of", "Само выбирающийся", "A self-clearing cache."),
    ("A self-purging of", "Само выбирающийся", "A self-purging database."),
    ("A self-cleaning of", "Само выбирающийся", "A self-cleaning oven."),
    ("A self-washing of", "Само выбирающийся", "A self-washing machine."),
    ("A self-drying of", "Само выбирающийся", "A self-drying clothes."),
    ("A self-ironing of", "Само выбирающийся", "A self-ironing shirt."),
    ("A self-folding of", "Само выбирающийся", "A self-folding laundry."),
    ("A self-organizing of", "Само выбирающийся", "A self-organizing system."),
    ("A self-arranging of", "Само выбирающийся", "A self-arranging furniture."),
    ("A self-sorting of", "Само выбирающийся", "A self-sorting algorithm."),
    ("A self-categorizing of", "Само выбирающийся", "A self-categorizing content."),
    ("A self-classifying of", "Само выбирающийся", "A self-classifying data."),
    ("A self-grouping of", "Само выбирающийся", "A self-grouping items."),
    ("A self-clustering of", "Само выбирающийся", "A self-clustering points."),
    ("A self-bunching of", "Само выбирающийся", "A self-bunching grapes."),
    ("A self-bundling of", "Само выбирающийся", "A self-bundling package."),
    ("A self-packing of", "Само выбирающийся", "A self-packing suitcase."),
    ("A self-wrapping of", "Само выбирающийся", "A self-wrapping gift."),
    ("A self-boxing of", "Само выбирающийся", "A self-boxing product."),
    ("A self-containerizing of", "Само выбирающийся", "A self-containerizing cargo."),
    ("A self-stacking of", "Само выбирающийся", "A self-stacking blocks."),
    ("A self-piling of", "Само выбирающийся", "A self-piling books."),
    ("A self-heaping of", "Само выбирающийся", "A self-heaping pile."),
    ("A self-accumulating of", "Само выбирающийся", "A self-accumulating wealth."),
    ("A self-collecting of", "Само выбирающийся", "A self-collecting data."),
    ("A self-gathering of", "Само выбирающийся", "A self-gathering information."),
    ("A self-assembling of", "Само выбирающийся", "A self-assembling furniture."),
    ("A self-constructing of", "Само выбирающийся", "A self-constructing building."),
    ("A self-building of", "Само выбирающийся", "A self-building structure."),
    ("A self-creating of", "Само выбирающийся", "A self-creating universe."),
    ("A self-generating of", "Само выбирающийся", "A self-generating content."),
    ("A self-producing of", "Само выбирающийся", "A self-producing energy."),
    ("A self-manufacturing of", "Само выбирающийся", "A self-manufacturing product."),
    ("A self-making of", "Само выбирающийся", "A self-making decision."),
    ("A self-forming of", "Само выбирающийся", "A self-forming pattern."),
    ("A self-shaping of", "Само выбирающийся", "A self-shaping material."),
    ("A self-molding of", "Само выбирающийся", "A self-molding clay."),
    ("A self-casting of", "Само выбирающийся", "A self-casting metal."),
    ("A self-forging of", "Само выбирающийся", "A self-forging sword."),
    ("A self-crafting of", "Само выбирающийся", "A self-crafting item."),
    ("A self-designing of", "Само выбирающийся", "A self-designing system."),
    ("A self-planning of", "Само выбирающийся", "A self-planning route."),
    ("A self-scheduling of", "Само выбирающийся", "A self-scheduling task."),
    ("A self-timing of", "Само выбирающийся", "A self-timing event."),
    ("A self-coordinating of", "Само выбирающийся", "A self-coordinating team."),
    ("A self-synchronizing of", "Само выбирающийся", "A self-synchronizing clock."),
    ("A self-aligning of", "Само выбирающийся", "A self-aligning text."),
    ("A self-adjusting of", "Само выбирающийся", "A self-adjusting seat."),
    ("A self-balancing of", "Само выбирающийся", "A self-balancing bike."),
    ("A self-stabilizing of", "Само выбирающийся", "A self-stabilizing drone."),
    ("A self-leveling of", "Само выбирающийся", "A self-leveling floor."),
    ("A self-flattening of", "Само выбирающийся", "A self-flattening surface."),
    ("A self-smoothing of", "Само выбирающийся", "A self-smoothing road."),
    ("A self-polishing of", "Само выбирающийся", "A self-polishing surface."),
    ("A self-buffing of", "Само выбирающийся", "A self-buffing floor."),
    ("A self-waxing of", "Само выбирающийся", "A self-waxing car."),
    ("A self-shining of", "Само выбирающийся", "A self-shining shoe."),
    ("A self-gleaming of", "Само выбирающийся", "A self-gleaming window."),
    ("A self-glowing of", "Само выбирающийся", "A self-glowing light."),
    ("A self-illuminating of", "Само выбирающийся", "A self-illuminating sign."),
    ("A self-lighting of", "Само выбирающийся", "A self-lighting candle."),
    ("A self-igniting of", "Само выбирающийся", "A self-igniting fuel."),
    ("A self-burning of", "Само выбирающийся", "A self-burning fire."),
    ("A self-consuming of", "Само выбирающийся", "A self-consuming process."),
    ("A self-devouring of", "Само выбирающийся", "A self-devouring monster."),
    ("A self-eating of", "Само выбирающийся", "A self-eating snake."),
    ("A self-digesting of", "Само выбирающийся", "A self-digesting food."),
    ("A self-absorbing of", "Само выбирающийся", "A self-absorbing material."),
    ("A self-soaking of", "Само выбирающийся", "A self-soaking sponge."),
    ("A self-drenching of", "Само выбирающийся", "A self-drenching rain."),
    ("A self-wetting of", "Само выбирающийся", "A self-wetting surface."),
    ("A self-moistening of", "Само выбирающийся", "A self-moistening soil."),
    ("A self-hydrating of", "Само выбирающийся", "A self-hydrating gel."),
    ("A self-watering of", "Само выбирающийся", "A self-watering plant."),
    ("A self-feeding of", "Само выбирающийся", "A self-feeding animal."),
    ("A self-nourishing of", "Само выбирающийся", "A self-nourishing organism."),
    ("A self-sustaining of", "Само выбирающийся", "A self-sustaining ecosystem."),
    ("A self-maintaining of", "Само выбирающийся", "A self-maintaining garden."),
    ("A self-caring of", "Само выбирающийся", "A self-caring person."),
    ("A self-tending of", "Само выбирающийся", "A self-tending garden."),
    ("A self-cultivating of", "Само выбирающийся", "A self-cultivating field."),
    ("A self-growing of", "Само выбирающийся", "A self-growing plant."),
    ("A self-blooming of", "Само выбирающийся", "A self-blooming flower."),
    ("A self-flowering of", "Само выбирающийся", "A self-flowering tree."),
    ("A self-fruiting of", "Само выбирающийся", "A self-fruiting tree."),
    ("A self-seeding of", "Само выбирающийся", "A self-seeding plant."),
    ("A self-reproducing of", "Само выбирающийся", "A self-reproducing organism."),
    ("A self-multiplying of", "Само выбирающийся", "A self-multiplying bacteria."),
    ("A self-dividing of", "Само выбирающийся", "A self-dividing cell."),
    ("A self-splitting of", "Само выбирающийся", "A self-splitting atom."),
    ("A self-breaking of", "Само выбирающийся", "A self-breaking wave."),
    ("A self-cracking of", "Само выбирающийся", "A self-cracking nut."),
    ("A self-shattering of", "Само выбирающийся", "A self-shattering glass."),
    ("A self-exploding of", "Само выбирающийся", "A self-exploding bomb."),
    ("A self-detonating of", "Само выбирающийся", "A self-detonating device."),
    ("A self-bursting of", "Само выбирающийся", "A self-bursting bubble."),
    ("A self-popping of", "Само выбирающийся", "A self-popping balloon."),
    ("A self-inflating of", "Само выбирающийся", "A self-inflating tire."),
    ("A self-expanding of", "Само выбирающийся", "A self-expanding foam."),
    ("A self-stretching of", "Само выбирающийся", "A self-stretching material."),
    ("A self-extending of", "Само выбирающийся", "A self-extending arm."),
    ("A self-reaching of", "Само выбирающийся", "A self-reaching goal."),
    ("A self-achieving of", "Само выбирающийся", "A self-achieving success."),
    ("A self-accomplishing of", "Само выбирающийся", "A self-accomplishing task."),
    ("A self-completing of", "Само выбирающийся", "A self-completing project."),
    ("A self-finishing of", "Само выбирающийся", "A self-finishing race."),
    ("A self-ending of", "Само выбирающийся", "A self-ending story."),
    ("A self-concluding of", "Само выбирающийся", "A self-concluding argument."),
    ("A self-closing of", "Само выбирающийся", "A self-closing door."),
    ("A self-shutting of", "Само выбирающийся", "A self-shutting window."),
    ("A self-sealing of", "Само выбирающийся", "A self-sealing envelope."),
    ("A self-locking of", "Само выбирающийся", "A self-locking mechanism."),
    ("A self-securing of", "Само выбирающийся", "A self-securing system."),
    ("A self-protecting of", "Само выбирающийся", "A self-protecting device."),
    ("A self-defending of", "Само выбирающийся", "A self-defending castle."),
    ("A self-guarding of", "Само выбирающийся", "A self-guarding treasure."),
    ("A self-shielding of", "Само выбирающийся", "A self-shielding material."),
    ("A self-covering of", "Само выбирающийся", "A self-covering blanket."),
    ("A self-wrapping of", "Само выбирающийся", "A self-wrapping gift."),
    ("A self-enveloping of", "Само выбирающийся", "A self-enveloping fog."),
]

# Функция initialize_srs_database удалена - используется напрямую в bot.py
